### ISSUE TITLE
Enhancements and streamlines

### ISSUE THREAD

**Issue by johnrharley** [AK-MCH-EPI/AK_COVID#1]
I appreciate you all creating a platform for distributing these data. 

There's a number of small tweaks that could be made to the shiny app here that would greatly boost speed and the readability of the code. Some simple things like not loading packages that aren't being used (as far as I can tell rjson and lubridate are not used, and there is overlap between dplyr and tidyr such that only one is needed) and removing verbose calls that do not appear to the end user (`str()` and `class()` for instance).

In terms of readability I agree with some of the internal comments that reproducing this with some of the dplyr language would help significantly. 

I don't know how much anyone is keeping up with this, but let me know if you'd like some help in the form of specific issues or if I can collaborate and submit a pull request.

**Comment by AK-MCH-EPI** [comment]
Thanks so much for looking at this. I had a research analyst who was learning how to build rshiny apps take some of my original developmental code and implement. Clearly they did some processing that results in redundant and slow loading. 

I only update the model now when needed given other demands on my time. I haven’t been using GitHub as a collaborative site but rather a place to host the code to promote transparency. I’ve constructed multiple far superior models, but this is the one that leadership felt most comfortable with…which is fine given that all of these models have major issues. 

I would love to have your collaboration if you’re willing

**Comment by AK-MCH-EPI** [comment]
I'm closing this issue. I did a complete update to the application, but it could still use a lot of improvement, let me know if you'd like to help out.
